user_name: test_user
provider: 阿里云百炼 (Aliyun)
model: qwen-plus
input_tokens_cost: 0.0008
output_tokens_cost: 0.002
classification_mode: classify_graph
long_log_threshold: 600
multi_purpose_app_names:
- chrome
- msedge
- firefox
lw_db_path: D:/desktop/软件开发/LifeWatch-AI/lifewatch/server/lifewatch_ai.db
aw_db_path: C:/Users/15535/AppData/Local/activitywatch/activitywatch/aw-server/peewee-sqlite.v2.db
chat_db_path: D:/desktop/软件开发/LifeWatch-AI/lifewatch/llm/llm_classify/chat/chat_history.db
data_cleaning_threshold: 10
